# Generated by Django 5.1.6 on 2025-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(upload_to='icon_image', verbose_name='Img')),
                ('names', models.CharField(max_length=255, verbose_name='names')),
                ('properties', models.CharField(max_length=250, verbose_name='properties')),
            ],
        ),
    ]
