# Generated by Django 5.1.6 on 2025-03-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_propertytypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypesJarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='icon_image', verbose_name='Img')),
                ('names', models.CharField(max_length=255, verbose_name='names')),
                ('properties', models.CharField(max_length=250, verbose_name='properties')),
            ],
        ),
        migrations.RemoveField(
            model_name='propertytypes',
            name='img',
        ),
        migrations.RemoveField(
            model_name='propertytypes',
            name='names',
        ),
        migrations.RemoveField(
            model_name='propertytypes',
            name='properties',
        ),
    ]
