# Generated by Django 5.1.6 on 2025-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_propertytypesjarang_remove_propertytypes_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='home_image', verbose_name='Imgs')),
                ('vernagir', models.CharField(max_length=255, verbose_name='vernagir')),
                ('texts', models.TextField(verbose_name='texts')),
            ],
        ),
    ]
