# Generated by Django 5.1.6 on 2025-03-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_moreinformation'),
        ('main', '0013_contactmodel'),
    ]

    operations = [
    ]
