# Generated by Django 5.1.6 on 2025-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_0004_moreinformation_0013_contactmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutStatus',
        ),
        migrations.DeleteModel(
            name='ClientOpinions',
        ),
        migrations.DeleteModel(
            name='ContactAgent',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='HomeStatus',
        ),
        migrations.RemoveField(
            model_name='submoreinfo',
            name='key',
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.DeleteModel(
            name='PropertyAgents',
        ),
        migrations.DeleteModel(
            name='PropertyListing',
        ),
        migrations.AlterField(
            model_name='imagecycle',
            name='img1',
            field=models.ImageField(null=True, upload_to='img1', verbose_name='img1'),
        ),
        migrations.AlterField(
            model_name='imagecycle',
            name='img2',
            field=models.ImageField(null=True, upload_to='img2', verbose_name='img2'),
        ),
        migrations.DeleteModel(
            name='MoreInfo',
        ),
        migrations.DeleteModel(
            name='SubMoreInfo',
        ),
    ]
