# Generated by Django 5.1.6 on 2025-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_homestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestatus',
            name='text2',
            field=models.CharField(max_length=255, null=True, verbose_name='text2'),
        ),
        migrations.AddField(
            model_name='homestatus',
            name='text3',
            field=models.CharField(max_length=255, null=True, verbose_name='text3'),
        ),
        migrations.AlterField(
            model_name='homestatus',
            name='text1',
            field=models.CharField(max_length=255, verbose_name='text1'),
        ),
        migrations.AlterField(
            model_name='homestatus',
            name='text4',
            field=models.CharField(max_length=255, null=True, verbose_name='text4'),
        ),
    ]
