# Generated by Django 5.1.6 on 2025-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_homestatus_text2_homestatus_text3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='img')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('npatak', models.CharField(max_length=255, verbose_name='npatak')),
                ('price', models.FloatField(verbose_name='price')),
                ('information', models.CharField(max_length=255, verbose_name='information')),
                ('adress', models.CharField(max_length=255, verbose_name='adress')),
                ('taracq', models.FloatField(verbose_name='taracq')),
                ('bed', models.IntegerField(verbose_name='bed')),
                ('bath', models.IntegerField(verbose_name='bath')),
            ],
        ),
    ]
