# Generated by Django 5.1.6 on 2025-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contactagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentimg', models.ImageField(upload_to='agentimg', verbose_name='agentimg')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('twitter', models.URLField(verbose_name='twitter')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('designation', models.CharField(max_length=255, verbose_name='designation')),
            ],
        ),
    ]
